name: Find and Replace url
on:
  push:
    branches:
      - main

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.URL_MASK }}"          
          git config --global user.email "brenovaladares27@gmail.com"
          git config --global user.name "ValadaresX"      
          git add .
          git commit -m "Replaced URL"
          git push
   
        


        



        
                     
      
