# Workflow para atualizar a URL base no arquivo main.yml
name: Update URL base in main.yml

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.url_base }}"

