name: Fluxo de Trabalho

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
      - name: Replace URL      
        env:
          URL_BASE: ${{ secrets.URL_MASK }}
        run: echo "A URL base é $URL_MASK"


