name: Find and Replace url
on:
  push:
    branches:
      - main

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3       

      - name: Replace URL
        run: |
          git diff --name-only HEAD^ | grep .py$ | while read -r file
          do
            sed -i 's|https://storage.googleapis.com/wowarenalogs-log-files-prod/|********|g' "$file"
            git add "$file"
          done
          git config --global user.email "brenovaladares27@gmail.com"
          git config --global user.name "Breno"
          git commit -m "Replaced URLs in .py files"

        



        
                     
      
