name: Find and Replace Example
on:
  push:
    branches:
      - main

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Imprimir o segredo
        env:
          MY_SECRET: ${{ secrets.URL_MASK }}
        run: echo $MY_SECRET

  