# Workflow para atualizar a URL base no arquivo main.yml
name: Update URL base in main.yml

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.SECRET_URL }}"

      - name: Echo a secret  
        run: echo "your secret token is ${{ secrets.SECRET_URL }}"
        shell: bash