name: Check and replace URL in .py files

on: 
  push:
    paths:
      - '**.py'

jobs:
  replace-url:
    runs-on: ubuntu-latest    
    steps:
      - name: Run Commands with a Secret
        env:
            SECRET_VALUE: ${{ secrets.URL__BASE }}
        run: |
          echo "Hello World"
          echo "This is a secret value: $SECRET_VALUE"
