# Controla quando a ação será executada.
on:
  # Aciona o workflow em eventos de push ou pull request, mas somente para o branch main.
  push:
    branches:
      - main

# Um workflow pode ter vários jobs, executados em sequência ou paralelamente.
jobs:
  # Este workflow contém um único job chamado "build".
  build:
    # O tipo de runner em que o job será executado.
    runs-on: ubuntu-latest

    # As steps representam uma sequência de tarefas que serão executadas como parte do job.
    steps:
      - name: Update URL base in script
        run: find . -name "copy_logs.py" -exec sed -i 's|url_base = .*|url_base = "******"|g' {} +
        shell: bash
    

          

     
