name: Find and Replace url
on:
  push:
    branches:
      - main

env:
  URL_MASK: ${{ secrets.URL_MASK }}
jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
